server:
  port:
    8085

spring:
  application:
    name:
      gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
            - "http://localhost:5001"
            - "http://localhost:5002"
            - "http://localhost:5003"
            - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders:
              - "Origin"
              - "Content-Type"
              - "Accept"
              - "Authorization"
              - "Referer"
            allowCredentials: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_FIRST
      routes:
        - id: AUTHENTICATION-SERVICE
          uri: http://localhost:5003
          predicates:
            - Path=/api/login/**
        - id: PAYMENT-SERVICE
          uri: http://localhost:5001
          predicates:
            - Path=/api/payments/**
        - id: USER-SERVICE
          uri: http://localhost:5002
          predicates:
            - Path=/api/users/**
    discovery:
      locator:
        lower-case-sensitive-id=true
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka